### PR TITLE
Fix deprecated PathService::getTemplatesPath() 

### PR DESCRIPTION
**Pull request by Macxim**
See #40.

### CODE REVIEW

**Comment by owldesign** [comment]
I'll merge this in later tonight, there are couple of other locations where I'd need to update the deprecated functions.

Thanks!

**Comment by Macxim** [comment]
No problem. Glad it's helpful. I wish I could fix the rest of them.

**Comment by Macxim** [comment]
@owldesign Actually, the [update to 2.6.2779](https://craftcms.com/changelog#build2779) fixes this.

> Fixed a PHP error that occurred when calling TemplatesService::getTemplatesPath().

**Comment by owldesign** [comment]
Yeah I saw that, but I might as well just update with new functions

**Comment by Macxim** [comment]
Definitely.

**Pull request merged**
